version: 0.0
os: linux

files:
  - source: app.jar
    destination: /home/ubuntu/app
  - source: scripts/
    destination: /home/ubuntu/app/scripts

hooks:
  BeforeInstall:
    - location: scripts/install.sh
      timeout: 300
      runas: root

  ApplicationStart:
    - location: scripts/start.sh
      timeout: 120
      runas: ubuntu
