server:
  port: 8080

spring:
  profiles:
    active: dev
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            redirect-uri: ${GOOGLE_REDIRECT_URI}
            scope: email, profile

          kakao:
            client-id: ${KAKAO_CLIENT_ID}
            client-secret: ${KAKAO_CLIENT_SECRET}
            redirect-uri: ${KAKAO_REDIRECT_URI}
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            scope: profile_nickname, account_email
            client-name: Kakao

        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth?prompt=consent

          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize?prompt=login
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

  cache:
    type: redis
    redis:
      time-to-live: ${REDIS_TTL}

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

toss:
  secret-key: ${TOSS_PAYMENTS_SECRET}

management:
  endpoint:
    health:
      show-details: always     # 선택사항: 헬스 체크 세부 정보 노출
  endpoints:
    web:
      exposure:
        include: health,info

---
spring:
  config:
    import: classpath:application-dev.properties
    activate:
      on-profile: dev

---
spring:
  config:
    import: classpath:application-prod.properties
    activate:
      on-profile: prod
